name: Sync Rating Database

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install Emacs
        run: sudo apt install -y emacs
      - name: Check out the Rating repository
        uses: actions/checkout@v4
        with:
          path: rating
      - name: Check out the Agenda repository
        uses: actions/checkout@v4
        with:
          repository: andreypudov/agenda
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: agenda
      - name: Sync Database
        run: rating/scripts/sync-database.sh
      - name: Export to HTML
        run: rating/scripts/export-to-html.sh
      - name: Update the repository
        run: |
          cd rating
          git config --global user.name 'Sync Rating Db'
          git config --global user.email 'sync-rating-db@users.noreply.github.com'
          git add .
          git commit -m "$(date -u +"%Y-%m-%d %H:%M:%SZ")"
          git push
